import { BusinessWalletTransaction } from '@/types/businessWalletTransaction';

export const dummyTransactions: BusinessWalletTransaction[] = [
  {
    id: '1',
    transactionId: 'G8QQvZ7MCM6LtJVakuFNJknY9DxnKVpY3HoWKRxiL9F',
    date: '-',
    category: 'Freight Forwarding',
    counterparty: 'Gandhi International Inc. - Chicago',
    notes: '',
    paymentMethod: 'Business Wallet (...3sw6)',
    status: 'draft',
    amount: '2234.00',
    currency: 'USDC',
  },
  {
    id: '2',
    transactionId: '5xWVxzUgMvfK4J4H1XH5qT9oEdMXP2WzRgVLCnYX7vNi',
    date: '2025-02-05T09:30:00Z',
    category: 'Ocean Carrier',
    counterparty: 'Koala Logistics LTD. - Sydney',
    notes: '',
    paymentMethod: 'Bank Account (CargoBill 4367)',
    status: 'scheduled',
    amount: '320.00',
    currency: 'EURC',
  },
  {
    id: '3',
    transactionId: 'AzLnKmR9e1PQYwx3o6BsFWuVZ7DcG5TgKtXy4H2JiNj8',
    date: '-',
    dueDate: '2025-01-01T12:00:00Z',
    category: 'Airline',
    counterparty: 'Malaysian Airways LLC. - Kuala',
    notes: '',
    paymentMethod: 'Credit Card (Chase 9876)',
    status: 'open',
    amount: '100.00',
    currency: 'USDC',
  },
  {
    id: '4',
    transactionId: 'EqS1U5pfVY3nzjKLbmRxT2Ga7o9QcW6ZhAiD8F4XvPdH',
    date: '2024-12-05T15:45:00Z',
    category: 'Ocean Carrier',
    counterparty: 'Koala Logistics LTD. - Sydney',
    notes: '',
    paymentMethod: 'Bank Account (CargoBill 4367)',
    status: 'cancelled',
    amount: '320.00',
    currency: 'EURC',
  },
  {
    id: '5',
    transactionId: 'N9kPmL3z7RwXvJqU2yBcF5sTaE8hGdQ6AiVoY1Z4xD0r',
    date: '2024-12-03T11:20:00Z',
    category: 'Freight Forwarding',
    counterparty: 'Intergateway Int. - Tokyo',
    notes: '',
    paymentMethod: 'Debit Card (...9876)',
    status: 'pending',
    amount: '540.00',
    currency: 'USDC',
  },
  {
    id: '6',
    transactionId: 'J1XaBf9L3oEkDzGqHsPwNiVTyv6c7R5AhU2m4KjYtZxW',
    date: '2024-11-26T14:15:00Z',
    category: 'Airline',
    counterparty: 'American Airlines Inc. - JFK',
    notes: '',
    paymentMethod: 'Checking (Chase 5892)',
    status: 'confirmed',
    amount: '10,454.00',
    currency: 'USDT',
  },
  {
    id: '7',
    transactionId: 'Tz8B3XrV1QoS6kP7JnLmCfY4NwAaD2GpEbHi9U5WeZyK',
    date: '2024-11-25T08:00:00Z',
    category: 'Airline',
    counterparty: 'American Airlines Inc. - JFK',
    notes: '',
    paymentMethod: 'Business Wallet (...3sw6)',
    status: 'completed',
    amount: '10,000.43',
    currency: 'USDC',
  },
];
